config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end 
    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories, only: [:new, :create, :show]
  resources :users, except: [:index, :destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable
  has_many :post_categories
  has_many :posts, through: :post_categories  
  validates :name, presence: true
  
  sluggable_column :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable 
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 3}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  sluggable_column :title
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable

  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 3 }, on: :create
  sluggable_column :username

  def is_admin?
  	self.role == 'admin'
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
	belongs_to :votable, polymorphic: true

	validates_uniqueness_of :creator, scope: [:votable_id, :votable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	if !current_user
  		flash[:error] = 'You need to be logged in'
  		redirect_to root_path
  	end
  end

  def require_admin
    access_denied unless logged_in? && current_user.is_admin?
  end

  def access_denied
    flash[:error] = "You can't do that."
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, except: [:show]
  before_action :require_admin, only: [:new, :create]
  
  def new
    binding.pry
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category created!'
      redirect_to :root
    else
      render 'new'
    end
  end

  def show
    @category = Category.find_by(slug: params[:id])
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Your comment was added"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
  	@comment = Comment.find(params[:id])
    @vote = Vote.create(votable: @comment, creator: current_user, vote: params[:vote])
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "You've voted!"
        else
          flash[:error] = "You've already voted!"
        end
        redirect_to :back
      end
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{ |x| x.total_votes}.reverse
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user
    if @post.save
      flash[:notice] = 'Your post was successfully created!'
      redirect_to :posts
    else
      render 'new'
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def show
    @comment = Comment.new
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Your post was successfully updated'
      redirect_to :post
    else
      render 'edit'
    end
  end

  def vote
    @vote = Vote.create(votable: @post, creator: current_user, vote: params[:vote])
    
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "You've voted!"
        else
          flash[:error] = "You've already voted!"
        end  
        redirect_to :back
      end
      format.js
    end
  end

  def require_creator
    access_denied unless logged_in? && (@post.creator == current_user || current_user.is_admin?)
  end

  private 
  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(username: params[:username]).authenticate(params[:password])

		if user
			flash[:notice] = "You've logged in!"
			session[:user_id] = user.id
			redirect_to root_path
		else
			flash[:error] = "Your username or password are incorrect! Please try again!"
			render 'new'
		end
	end

	def destroy
		session.clear
		flash[:notice] = "You've been logged out!"
		redirect_to root_path
	end

	private
	def post_params
		params.permit(:username, :password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# before_action :require_user, except: [:new, :show]
	before_action :set_user, only: [:show, :edit, :update]
	before_action :require_same_user, only: [:edit, :update]

	def new
		@user = User.new
	end

	def create
		@user = User.new(post_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = 'Your account was created!'
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		if !@user
			flash[:error] = "You're not allowed to do that"
			redirect_to root_path
		end
	end

	def update
		if @user.update(post_params)
			flash[:notice] = "Your profile was updated"
			redirect_to user_path
		else
			render 'edit'
		end
	end

	def show
	end

	private
	def post_params
		params.require(:user).permit(:username, :password, :timezone)
	end

	def set_user
		@user = User.find_by(slug: params[:id])
	end

	def require_same_user
		if current_user != @user
			flash[:error] = "Your not allowed to do that!"
			redirect_to root_path
		end
	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.starts_with?('http://') ? str : "http://#{str}"
  end

  def format_date(date)
  	if logged_in? && !current_user.timezone.blank?
  		date = date.in_time_zone(current_user.timezone)
  	end
    date.strftime("at %d/%m/%Y %H:%M %Z")
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<div class='well'>
<%= form_for @category do |f| %>
  <div class="control-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(@category.new_record? ? 'Create Category' : 'Update Category', class: 'btn btn-primary') %>
<% end %>
</div>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: 'All Categories' %>

<% @categories.each do |category| %>
  <div class="well">
    <h3><%= link_to category.name, category_path(category) %></h3>
  </div>
<% end %>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'New Category' %>
<%= render 'shared/errors', errors: @category.errors %>
<%= render 'form' %>

app/views/categories/show.html.erb
<% all_posts = link_to('All Posts', posts_path) %>

<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@category.name}".html_safe %>


<% @category.posts.each do |post| %>
    <%= render 'posts/post', post: post %>
<% end %>

app/views/comments/_comment.html.erb
<% show_post ||= false %>
<div class="row">
	<div class="span0 well text-center">
		<% if logged_in? %>
			<%= link_to (vote_post_comment_path(comment.post, comment, vote: true)), method: 'post', remote: true do %>
	      <li class="icon-arrow-up"></li>
	    <% end %>
	    <br/>
		<% end %>
    <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %> votes</span>
    <% if logged_in? %>
    	<br/>
    	<%= link_to (vote_post_comment_path(comment.post, comment, vote: false)), method: 'post', remote: true do %>
      	<li class="icon-arrow-down"></li>
    	<% end %>	
    <% end %>
  </div>
	<div class="well span8">
	  <em><%= comment.body %></em>
	  <% if show_post %>
	  	on <%= link_to comment.post.title, post_path(comment.post) %>
	  <% end %>
	  <br/>
	  <span class="quiet">by</span> <%= link_to comment.creator.username, user_path(comment.creator) %>
	  <small><%= format_date(comment.created_at) %></small>
	</div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
	$("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes %> votes")
<% else %>
	alert('You can vote a comment once!')
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>
<div class='btn-group nav_item'>
<%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
  Categories <span class='caret'></span>
  <% end %>
  <ul class='dropdown-menu'>
    <% Category.all.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
    <% if logged_in? %>
    <% if current_user.is_admin? %>
        <li class='divider'></li>
        <li>
          <%= link_to(new_category_path) do  %>
            <i class="icon-plus"></i>
            New Category
          <% end %>
        </li>
      <% end %>    
    <% end %>
  </ul>
</div>

<div class='nav_item'>
  <% if logged_in? %>
    <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
  <% else %>
    <%= link_to "Register", register_path, class: 'btn btn-success btn-small' %>
  <% end %>
</div>

<div class='btn-group nav_item'>
  <% if !logged_in? %>
    <div class='nav_item'>
      <%= link_to 'Log in', login_path, class: 'btn btn-small' %>
    </div>
  <% else %>
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    <%= current_user.username %> <span class='caret'></span>
    <% end %>
    <ul class='dropdown-menu'>
      <li>
        <%= link_to edit_user_path(current_user) do %>
          <i class='icon-pencil'></i>
          Edit profile
        <% end %>
      </li>
      <li>
        <%= link_to user_path(current_user)  do %>
          <i class='icon-user'></i>
          View profile
        <% end %>
      </li>
      <li>
        <%= link_to logout_path  do %>
          <i class='icon-circle-arrow-left'></i>
          Logout
        <% end %>
      </li>
    </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for post do |f| %>
<div class='well'>
  <div class="control-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="control-group">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="control-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  <div class="control-group">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>
  <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
</div>
<% end %>

app/views/posts/_post.html.erb
<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to (vote_post_path(post, vote: true)), method: 'post', remote: true do %>
        <li class="icon-arrow-up"></li>
      <% end %>
      <br/>
    <% end %>
    <span id='<%= "post_#{post.id}_votes" %>'><%= post.total_votes %> votes</span>
    <% if logged_in? %>
      <br/>
      <%= link_to (vote_post_path(post, vote: false)), method: 'post', remote: true do %>
        <li class="icon-arrow-down"></li>
      <% end %>
    <% end %>
  </div>
  <div class="span8 well">
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small><%= format_date(post.created_at) %></small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Posts' %>

<%= render 'shared/errors', errors: @post.errors %>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Add New Post' %>
<%= render 'shared/errors', errors: @post.errors %>
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class='pull-right'>
    [<%= link_to 'edit this post', edit_post_path(@post) %>]
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>

<% if logged_in? %>
  <%= form_for [@post,@comment] do |f| %>
    <%= render 'shared/errors', errors: @comment.errors %>
    <%= f.label :body, 'Leave a comment' %>
    <%= f.text_area :body %>
    <br/>
    <%= f.submit 'Add a Comment', class: 'btn btn-primary' %>
  <% end %>
<% end %>

<h5>Comments:</h5>
<% @post.reload.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
	$("#post_<%= @post.id %>_votes").html(<%= @post.total_votes %>);
<% else %>
	alert('You can vote a post once!')
<% end %>

app/views/shared/_content_title.html.erb
<h1>
  <%= title %>
</h1>
<hr>

app/views/shared/_errors.html.erb
<% if errors.any? %>
  <div class="alert alert-error">
    <ul>
      <% errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end  %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="span4 well">
<%= form_for user do |f| %>
	<div class="control-group">
		<%= f.label :username %>
		<%= f.text_field :username %>
	</div>
	<div class="control-group">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div class="control-group">
		<%= f.label :timezone %>
		<%= f.time_zone_select :timezone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name %>
	</div>
	<br>
	<%= f.submit (@user.new_record? ? "Create User" : "Update User"), class: "btn btn-primary" %>
<% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Profile' %>

<%= render 'shared/errors', errors: @user.errors %>

<%= render 'form', user: @user %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'New User Registration Form' %>
<%= render 'shared/errors', errors: @user.errors %>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>

<div class="well">
  <dl class="dl-horizontal">
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
    <dt>Time zone:</dt>
    <dd><%= @user.timezone %></dd>
  </dl>
</div>

<div class='nav nav-tabs'>
  <li class='<%= 'active' if params[:tab].nil? %>'>
  <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
  </li>
  <li class='<%= 'active' if params[:tab] == 'comments' %>'>
  <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %>
  </li>
</div>

<% if params[:tab].nil? %>
  <% @user.posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>
<% elsif params[:tab] == 'comments' %>
    <% @user.comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment, show_post: true %>
    <% end %>
<% end %>